language: shell
addons:
  artifacts:
    paths:
    - $(ls $TRAVIS_BUILD_DIR/*.zip)
    - $(ls $TRAVIS_BUILD_DIR/*.dmg)
    target_paths:
    - /m64p
jobs:
  include:
  - stage: build-linux
    dist: bionic
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y dist-upgrade
    - sudo apt-get -y install cmake libhidapi-dev lsb-release wget libminizip-dev libsdl2-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev pkg-config zlib1g-dev binutils-dev libspeexdsp-dev libsamplerate0-dev qt5-default build-essential nasm git zip libsdl2-net-dev libqt5websockets5-dev
    script:
    - bash ./build.sh
  - stage: build-windows
    env:
    - MSYSTEM=MINGW64
    - myarch=x86_64
    - MSYS2_DIR=msys64
    os: windows
    before_install:
    - rm -rf /C/tools/msys64
    - choco uninstall -y mingw
    - choco upgrade --no-progress -y msys2
    - "cmd //C RefreshEnv.cmd"
    - export PATH=/C/tools/$MSYS2_DIR/$MSYSTEM/bin:/C/tools/$MSYS2_DIR/usr/bin:$PATH
    script:
    - pacman --sync --clean --noconfirm
    - pacman -Syu --noconfirm
    - pacman -Syu --noconfirm
    - pacman -S --needed --noconfirm make mingw-w64-$myarch-cmake mingw-w64-$myarch-gcc mingw-w64-$myarch-hidapi mingw-w64-$myarch-freetype mingw-w64-$myarch-libpng mingw-w64-$myarch-libsamplerate mingw-w64-$myarch-SDL2 mingw-w64-$myarch-SDL2_net mingw-w64-$myarch-jasper mingw-w64-$myarch-qt5 mingw-w64-$myarch-python3-pip mingw-w64-$myarch-python3-pyopenssl zip
    - export HOST_CPU=$myarch; ./build.sh
